services:
  db:
    build:
      context: ../
      dockerfile: docker/Dockerfile.db
    container_name: itb745_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile.web
    container_name: itb745_web
    depends_on:
      - db
    ports:
      - "8080:8000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
