# ---
# - name: Initialize Docker Swarm on Manager
#   hosts: manager
#   become: yes
#   tasks:
#     - name: Init Swarm
#       shell: docker swarm init --advertise-addr {{ ansible_host }}
#       register: swarm_init
#       ignore_errors: yes

#     - name: Get Worker Join Token
#       shell: docker swarm join-token worker -q
#       register: worker_token

#     - name: Save Worker Join Token
#       set_fact:
#         join_token: "{{ worker_token.stdout }}"

# - name: Join Workers to Swarm
#   hosts: workers
#   become: yes
#   tasks:
#     - name: Join Swarm as Worker
#       shell: docker swarm join --token {{ hostvars['174.129.123.30'].join_token }} 174.129.123.30:2377
#       ignore_errors: yes
---
# =========================================================
#  Docker Swarm Initialization - Auto-detect Manager IP
#  For ITB745 | mru-Controller, mru-Manager, mru-Workers
# =========================================================

- name: Initialize Docker Swarm on Manager
  hosts: manager
  become: yes
  tasks:
    - name: Get Manager IP address dynamically
      ansible.builtin.shell: hostname -I | awk '{print $1}'
      register: manager_ip

    - name: Initialize Docker Swarm (ignore if already initialized)
      ansible.builtin.shell: docker swarm init --advertise-addr {{ manager_ip.stdout }}
      register: swarm_init
      ignore_errors: yes

    - name: Get worker join token
      ansible.builtin.shell: docker swarm join-token worker -q
      register: worker_token

    - name: Save join token as fact
      set_fact:
        swarm_join_token: "{{ worker_token.stdout }}"
        swarm_manager_ip: "{{ manager_ip.stdout }}"


- name: Join Workers to Docker Swarm
  hosts: workers
  become: yes
  vars:
    manager_ip: "{{ hostvars[groups['manager'][0]].swarm_manager_ip }}"
    join_token: "{{ hostvars[groups['manager'][0]].swarm_join_token }}"
  tasks:
    - name: Join worker node to swarm
      ansible.builtin.shell: docker swarm join --token {{ join_token }} {{ manager_ip }}:2377
      ignore_errors: yes
