name: Deploy to Swarm

on:
  push:
    branches: [ ITA771 ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Swarm Manager
      env:
        SSH_PRIVATE_KEY: ${{ secrets.-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEA0XUYZKBbMh0TQKk+FbePZZFqn5uRwVJ4oH/HVAFQkM6l7MQQcBlW
SLe0D2PHMgibuItbEAD0GsBUWCZvRxkCmzGdtxnCFFCAKBFculP5EpsQ/9qYYKfhCjZXmq
3QdRBtx/NvHqSiRybaJ6gBQymuNNdN3K5qFXMLaaU9gvMtp8eKTmYSpM4woMcWp6Qm6P9Y
P5JCSObK94MO1W/G16WrIPd6DGV8A0fXfWkrhCUIDN/fXWRBv6+m8ZWxwGAya8x9FvXNzA
qzp6PRgULY1EzGikL9+Z2/7nFi1nSD6WVIFYMdHi8WgQiHyZatMsyE0p6V9Gi+E4LsHyXO
qrVqaMcpUeFlXE65lwWUYCFPCRu/DEh7KdYR465tb2AzCVy4O+pScpZOpMCdfdsFv6zBkA
Jv2Rvjtp59UIf/4XQ77PWlnjaHTQ0kGsTf6wphoU0kNtR+drcdFTWTiTR97Xp42EiEpmQT
0GmPXlT5vqFXLDsHwJCd+vEMvIWjlgiR8KpHUIgvF83GwiMrXRMezQ66bvh81Sqo1x0T3M
ZRpGCqm40cO4d5wa/qRJ84bYtjKXWYPGnWTDk0LTNiclBmNBVZvm0/yu7XpOWo6Mbe1Yub
9qU3a4DTrPa/AY9Di50bFO+o0AM5svPqJyy82V3mFOapPDo857s9t8TkGaKxCnARv9H8gm
8AAAdQhf5ZxYX+WcUAAAAHc3NoLXJzYQAAAgEA0XUYZKBbMh0TQKk+FbePZZFqn5uRwVJ4
oH/HVAFQkM6l7MQQcBlWSLe0D2PHMgibuItbEAD0GsBUWCZvRxkCmzGdtxnCFFCAKBFcul
P5EpsQ/9qYYKfhCjZXmq3QdRBtx/NvHqSiRybaJ6gBQymuNNdN3K5qFXMLaaU9gvMtp8eK
TmYSpM4woMcWp6Qm6P9YP5JCSObK94MO1W/G16WrIPd6DGV8A0fXfWkrhCUIDN/fXWRBv6
+m8ZWxwGAya8x9FvXNzAqzp6PRgULY1EzGikL9+Z2/7nFi1nSD6WVIFYMdHi8WgQiHyZat
MsyE0p6V9Gi+E4LsHyXOqrVqaMcpUeFlXE65lwWUYCFPCRu/DEh7KdYR465tb2AzCVy4O+
pScpZOpMCdfdsFv6zBkAJv2Rvjtp59UIf/4XQ77PWlnjaHTQ0kGsTf6wphoU0kNtR+drcd
FTWTiTR97Xp42EiEpmQT0GmPXlT5vqFXLDsHwJCd+vEMvIWjlgiR8KpHUIgvF83GwiMrXR
MezQ66bvh81Sqo1x0T3MZRpGCqm40cO4d5wa/qRJ84bYtjKXWYPGnWTDk0LTNiclBmNBVZ
vm0/yu7XpOWo6Mbe1Yub9qU3a4DTrPa/AY9Di50bFO+o0AM5svPqJyy82V3mFOapPDo857
s9t8TkGaKxCnARv9H8gm8AAAADAQABAAACAQCjCdd79EooPvOOgG5gLyrCb6ekJ08UQSK+
I9g/LmrM3N3Q52i4KTC9l6jj1dHmw0abJnYyhdt8uzqsBvbVS8V4ke1m6fjlISgwiBs6uk
SFVAiubzPvAJ4t+dDFCQjbJnedjYJwQsxCQB7NgXvCEL6WSQVFgsn2ej9m84Vm2e0uzSZ+
EfvvJsQ5Ud7zjNXwxVmm2i0YW/WfJfe08bXAhCcpmRj6b0BRuWkmKGgEC2Mxyk0uf+yhzZ
NQNypOSVLWEC1KYvjXG3luQxi/2g23ay+bzbutwjn023OI5NcNJJYwkIdoyFRnCgHQS6Xz
hbjZzTGCNsnFnEI5mI8+18nFV0l0FxhcqRMux8BruoDZYPR4dXqHb2hnDhshqOMV/wzEUH
LflMn3ZMyKOo0RrGxuVfzrHRDPJF6RHoiAhlrG6fjIN2mHTNvcb05fRCE9lSpHN6JPUAlT
4JWUZv7zsjLJvhQE1l073xNRqmZ+oNIcauNDr8YyHQM2lfEDEsMBM5Fd+cFpoQYT2U+len
LpJyHyZViYAMl3AGirMhQ3+uR4dkO1x1hKow+EEQVv24YUDwKctucsbEb6Ha7SwSM9zZ2t
aeSsQR125T6oLpPZOxADDFEQNPQRQHWDLgi0k+lMEpdPCgKoxaEBDMJVpLJiUqOuk8HEFw
g4bHTTOz7Gy5fyeeeICQAAAQBS2ycLm/P21V7t+U3mOFaHa/B4AwzxUMDaFzhlBGd8VAK+
+y99YSArA5IxUSTvM1sjJingudIJl0nf5VuG6o0q97a5i8RGgZoh2UODmHoWhWl9rTkSXt
Sqzn1pub8dQOu7QtQarSDF94hARVbGnwvmFQDoHVHmLjwEEN3C3iWis0nuuaJ8kkNfwQfe
Yd+rdQClW4uP5jGRRKfyU2S0ZvUK3MRjT5+u8m1Mk8i418kz3SWwnM4C8yJv9cR8+GLMW+
2KwlMVecf/ylKqHnGhFFZ9kYxmcJTxbNYsY2D23/bPPoWgFjqMmO9EfgdTzMk9hWl+YGDY
l0oF6n7gukaFi9L/AAABAQDwGSY+IredPLnw699+bXIuJmFRvMwdqVbF8Dlm+Z6TtaRflh
F02RVgYKzWLbTnhsTLfghMCa70JzCy/Fm3VHemtvmXVPZNboqH7sTM9Y93mZXm570jNCgw
plYBZK01Dk4MoFSP+wzfr9bCiKYcTxh/EkcM0fM9IeEkVOeXdB9qcRgy7yfUHZrKYKKReB
z3U/25nl0qTwnaa0OtuMC32m9DKy0a1a2C2pacBeHDLWROs2J6YvsAusc6xB+1GRyQLqIv
AdMh9eKvJ0vNR10YonbnthA41LHXoak+ZG0P+4Xg/bLlCCxOwuSVLOsMSKkRdpx5uAFcNL
v/+X7vuT3HNc1VAAABAQDfVG60WSXhW73hhDLk91hiEXkNUEHP74+fR9TNTEzeTBIMVqWU
M71WrASQR8EO0e3mGW5xYEctRhHUhGe8W95sHVqRuGSUdG4m4be4JwEALYOEDVF6ZnW7mL
VkOF2i6EqrdSN+5GbobGQ87UKNoMLpUHoZcobf+hYRTsFeaH6UF63YE8sR6G8DuUuQm/cQ
4IK5qfCY6EPs6+w1Pk6pk53U+uE5uySYSWFmo+zYPLUADZLQzQTUMLOcYBGckgOtjZU3cY
h2kypRm7UWVKZBABBlAQRNbj1z74jo/8r/YXwMqDYnfmXZWPnpo2yKnvTjlxZajqSTTe+9
J0r5TH0dZjCzAAAAF3VidW50dUBpcC0xNzItMzEtMTgtMTg4AQID
-----END OPENSSH PRIVATE KEY----- }}
        MANAGER_IP: ${{ secrets.75.101.222.153 }}
      run: |
        mkdir -p ~/.ssh
        echo "-----BEGIN OPENSSH PRIVATE KEY----- b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn NhAAAAAwEAAQAAAgEA0XUYZKBbMh0TQKk+FbePZZFqn5uRwVJ4oH/HVAFQkM6l7MQQcBlW SLe0D2PHMgibuItbEAD0GsBUWCZvRxkCmzGdtxnCFFCAKBFculP5EpsQ/9qYYKfhCjZXmq 3QdRBtx/NvHqSiRybaJ6gBQymuNNdN3K5qFXMLaaU9gvMtp8eKTmYSpM4woMcWp6Qm6P9Y P5JCSObK94MO1W/G16WrIPd6DGV8A0fXfWkrhCUIDN/fXWRBv6+m8ZWxwGAya8x9FvXNzA qzp6PRgULY1EzGikL9+Z2/7nFi1nSD6WVIFYMdHi8WgQiHyZatMsyE0p6V9Gi+E4LsHyXO qrVqaMcpUeFlXE65lwWUYCFPCRu/DEh7KdYR465tb2AzCVy4O+pScpZOpMCdfdsFv6zBkA Jv2Rvjtp59UIf/4XQ77PWlnjaHTQ0kGsTf6wphoU0kNtR+drcdFTWTiTR97Xp42EiEpmQT 0GmPXlT5vqFXLDsHwJCd+vEMvIWjlgiR8KpHUIgvF83GwiMrXRMezQ66bvh81Sqo1x0T3M ZRpGCqm40cO4d5wa/qRJ84bYtjKXWYPGnWTDk0LTNiclBmNBVZvm0/yu7XpOWo6Mbe1Yub 9qU3a4DTrPa/AY9Di50bFO+o0AM5svPqJyy82V3mFOapPDo857s9t8TkGaKxCnARv9H8gm 8AAAdQhf5ZxYX+WcUAAAAHc3NoLXJzYQAAAgEA0XUYZKBbMh0TQKk+FbePZZFqn5uRwVJ4 oH/HVAFQkM6l7MQQcBlWSLe0D2PHMgibuItbEAD0GsBUWCZvRxkCmzGdtxnCFFCAKBFcul P5EpsQ/9qYYKfhCjZXmq3QdRBtx/NvHqSiRybaJ6gBQymuNNdN3K5qFXMLaaU9gvMtp8eK TmYSpM4woMcWp6Qm6P9YP5JCSObK94MO1W/G16WrIPd6DGV8A0fXfWkrhCUIDN/fXWRBv6 +m8ZWxwGAya8x9FvXNzAqzp6PRgULY1EzGikL9+Z2/7nFi1nSD6WVIFYMdHi8WgQiHyZat MsyE0p6V9Gi+E4LsHyXOqrVqaMcpUeFlXE65lwWUYCFPCRu/DEh7KdYR465tb2AzCVy4O+ pScpZOpMCdfdsFv6zBkAJv2Rvjtp59UIf/4XQ77PWlnjaHTQ0kGsTf6wphoU0kNtR+drcd FTWTiTR97Xp42EiEpmQT0GmPXlT5vqFXLDsHwJCd+vEMvIWjlgiR8KpHUIgvF83GwiMrXR MezQ66bvh81Sqo1x0T3MZRpGCqm40cO4d5wa/qRJ84bYtjKXWYPGnWTDk0LTNiclBmNBVZ vm0/yu7XpOWo6Mbe1Yub9qU3a4DTrPa/AY9Di50bFO+o0AM5svPqJyy82V3mFOapPDo857 s9t8TkGaKxCnARv9H8gm8AAAADAQABAAACAQCjCdd79EooPvOOgG5gLyrCb6ekJ08UQSK+ I9g/LmrM3N3Q52i4KTC9l6jj1dHmw0abJnYyhdt8uzqsBvbVS8V4ke1m6fjlISgwiBs6uk SFVAiubzPvAJ4t+dDFCQjbJnedjYJwQsxCQB7NgXvCEL6WSQVFgsn2ej9m84Vm2e0uzSZ+ EfvvJsQ5Ud7zjNXwxVmm2i0YW/WfJfe08bXAhCcpmRj6b0BRuWkmKGgEC2Mxyk0uf+yhzZ NQNypOSVLWEC1KYvjXG3luQxi/2g23ay+bzbutwjn023OI5NcNJJYwkIdoyFRnCgHQS6Xz hbjZzTGCNsnFnEI5mI8+18nFV0l0FxhcqRMux8BruoDZYPR4dXqHb2hnDhshqOMV/wzEUH LflMn3ZMyKOo0RrGxuVfzrHRDPJF6RHoiAhlrG6fjIN2mHTNvcb05fRCE9lSpHN6JPUAlT 4JWUZv7zsjLJvhQE1l073xNRqmZ+oNIcauNDr8YyHQM2lfEDEsMBM5Fd+cFpoQYT2U+len LpJyHyZViYAMl3AGirMhQ3+uR4dkO1x1hKow+EEQVv24YUDwKctucsbEb6Ha7SwSM9zZ2t aeSsQR125T6oLpPZOxADDFEQNPQRQHWDLgi0k+lMEpdPCgKoxaEBDMJVpLJiUqOuk8HEFw g4bHTTOz7Gy5fyeeeICQAAAQBS2ycLm/P21V7t+U3mOFaHa/B4AwzxUMDaFzhlBGd8VAK+ +y99YSArA5IxUSTvM1sjJingudIJl0nf5VuG6o0q97a5i8RGgZoh2UODmHoWhWl9rTkSXt Sqzn1pub8dQOu7QtQarSDF94hARVbGnwvmFQDoHVHmLjwEEN3C3iWis0nuuaJ8kkNfwQfe Yd+rdQClW4uP5jGRRKfyU2S0ZvUK3MRjT5+u8m1Mk8i418kz3SWwnM4C8yJv9cR8+GLMW+ 2KwlMVecf/ylKqHnGhFFZ9kYxmcJTxbNYsY2D23/bPPoWgFjqMmO9EfgdTzMk9hWl+YGDY l0oF6n7gukaFi9L/AAABAQDwGSY+IredPLnw699+bXIuJmFRvMwdqVbF8Dlm+Z6TtaRflh F02RVgYKzWLbTnhsTLfghMCa70JzCy/Fm3VHemtvmXVPZNboqH7sTM9Y93mZXm570jNCgw plYBZK01Dk4MoFSP+wzfr9bCiKYcTxh/EkcM0fM9IeEkVOeXdB9qcRgy7yfUHZrKYKKReB z3U/25nl0qTwnaa0OtuMC32m9DKy0a1a2C2pacBeHDLWROs2J6YvsAusc6xB+1GRyQLqIv AdMh9eKvJ0vNR10YonbnthA41LHXoak+ZG0P+4Xg/bLlCCxOwuSVLOsMSKkRdpx5uAFcNL v/+X7vuT3HNc1VAAABAQDfVG60WSXhW73hhDLk91hiEXkNUEHP74+fR9TNTEzeTBIMVqWU M71WrASQR8EO0e3mGW5xYEctRhHUhGe8W95sHVqRuGSUdG4m4be4JwEALYOEDVF6ZnW7mL VkOF2i6EqrdSN+5GbobGQ87UKNoMLpUHoZcobf+hYRTsFeaH6UF63YE8sR6G8DuUuQm/cQ 4IK5qfCY6EPs6+w1Pk6pk53U+uE5uySYSWFmo+zYPLUADZLQzQTUMLOcYBGckgOtjZU3cY h2kypRm7UWVKZBABBlAQRNbj1z74jo/8r/YXwMqDYnfmXZWPnpo2yKnvTjlxZajqSTTe+9 J0r5TH0dZjCzAAAAF3VidW50dUBpcC0xNzItMzEtMTgtMTg4AQID -----END OPENSSH PRIVATE KEY-----" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $MANAGER_IP >> ~/.ssh/known_hosts
        
        
        scp -r docker-compose.yml ubuntu@75.101.222.153:/tmp/
        
        
        ssh ubuntu@75.101.222.153 "cd /tmp && docker stack deploy -c docker-compose.yml myapp"
